---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-export-dynamic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-export-csi
