apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-export-csi
provisioner: nfs-export.csi.k8s.io
parameters:
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"

  backendStorageClass: microk8s-hostpath
  backendPodImage: daocloud.io/piraeus/volume-nfs-exporter:ganesha
  backendNamespace: csi-nfs-export

reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1