apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-export-csi
provisioner: nfs-export.csi.k8s.io
parameters:
  dataStorageClass: "" # use default StorageClass
  nfsServerImage: "" # default image: daocloud.io/piraeus/nfs-ganesha:latest
  # nfsServerImage: daocloud.io/piraeus/nfs-server:latest
  nfsHostsAllow: "" # auto-detect host ip (not implemented yet)
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1