---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-nfs-export-controller
  labels:
    nfs-export.csi.k8s.io/server: controller
spec:
  replicas: {{ .Values.controllerReplicas }}
  selector:
    matchLabels:
      nfs-export.csi.k8s.io/server: controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        nfs-export.csi.k8s.io/server: controller
    spec:
      terminationGracePeriodSeconds: 0
      hostNetwork: true  # controller also needs to mount nfs to create dir
      dnsPolicy: Default  # available values: {{ .Release.Namespace }}, ClusterFirstWithHostNet, ClusterFirst
      serviceAccountName: csi-nfs-export-controller-sa
      nodeSelector:
        kubernetes.io/os: linux  # add "kubernetes.io/role: master" to run controller on master node
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/controlplane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: provisioner
          image: {{ .Values.provisioner.image }}
          imagePullPolicy: {{ .Values.provisioner.imagePullPolicy }}
          args:
            - "-v=2"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
            - "--leader-election-namespace=$(NAMESPACE)"
            - "--extra-create-metadata=true"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
          resources: {}
        - name: liveness-probe
          image: {{ .Values.livenessProbe.image }}
          imagePullPolicy: {{ .Values.livenessProbe.imagePullPolicy }}
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --health-port=29652
            - --v=2
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          resources: {}
        - name: plugin
          image: {{ .Values.plugin.image }}
          imagePullPolicy: {{ .Values.plugin.imagePullPolicy }}
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          args:
            - "-v=5"
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
          env:   
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          ports:
            - containerPort: 29652
              name: healthz
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
          volumeMounts:
            - name: pods-mount-dir
              mountPath: {{ .Values.kubeletRoot }}/pods
              mountPropagation: "Bidirectional"
            - mountPath: /csi
              name: socket-dir
          resources: {}
      volumes:
        - name: pods-mount-dir
          hostPath:
            path: {{ .Values.kubeletRoot }}/pods
            type: Directory
        - name: socket-dir
          emptyDir: {}