---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: nfs-export.csi.k8s.io
spec:
  attachRequired: false
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
  fsGroupPolicy: File
  podInfoOnMount: true
